//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisciplineReviews
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseReview
    {
        public int CourseReviewID { get; set; }
        public int CourseID { get; set; }
        public string Comment { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Easyness { get; set; }
        public Nullable<int> Interests { get; set; }
        public Nullable<int> Clarity { get; set; }
        public Nullable<int> Usability { get; set; }
        public Nullable<int> Grade { get; set; }
        public int CourseUp { get; set; }
        public int CourseDown { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual User User { get; set; }
    }
}
