//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisciplineReviews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.CourseReviews = new HashSet<CourseReview>();
            this.CoursesToTeachers = new HashSet<CoursesToTeacher>();
            this.CoursesToUsers = new HashSet<CoursesToUser>();
        }
    
        public int CourseID { get; set; }
        public int DisciplineID { get; set; }
        public int LeaderID { get; set; }
    
        public virtual ICollection<CourseReview> CourseReviews { get; set; }
        public virtual Discipline Discipline { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<CoursesToTeacher> CoursesToTeachers { get; set; }
        public virtual ICollection<CoursesToUser> CoursesToUsers { get; set; }
    }
}
