//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisciplineReviews
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursesToTeacher
    {
        public int CourseToTeacherID { get; set; }
        public int TeacherID { get; set; }
        public int CourseID { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
