//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisciplineReviews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipline
    {
        public Discipline()
        {
            this.Courses = new HashSet<Cours>();
        }
    
        public int DisciplineID { get; set; }
        public string DisciplineName { get; set; }
        public decimal DisciplineCredits { get; set; }
        public int TypeID { get; set; }
    
        public virtual ICollection<Cours> Courses { get; set; }
        public virtual Type Type { get; set; }
    }
}
