//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisciplineReviews
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DisciplineReviewsEntities : DbContext
    {
        public DisciplineReviewsEntities()
            : base("name=DisciplineReviewsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CourseReview> CourseReviews { get; set; }
        public DbSet<Cours> Courses { get; set; }
        public DbSet<CoursesToTeacher> CoursesToTeachers { get; set; }
        public DbSet<CoursesToUser> CoursesToUsers { get; set; }
        public DbSet<Discipline> Disciplines { get; set; }
        public DbSet<TeacherReview> TeacherReviews { get; set; }
        public DbSet<Teacher> Teachers { get; set; }
        public DbSet<Type> Types { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
