//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisciplineReviews
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherReview
    {
        public int TeacherReviewID { get; set; }
        public int TeacherID { get; set; }
        public int TeacherUp { get; set; }
        public int TeacherDown { get; set; }
        public int Clarity { get; set; }
        public int Criteria { get; set; }
        public int Speed { get; set; }
        public int Material { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
