//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisciplineReviews
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CourseReviews = new HashSet<CourseReview>();
            this.CoursesToUsers = new HashSet<CoursesToUser>();
            this.Teachers = new HashSet<Teacher>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> FacNumber { get; set; }
    
        public virtual ICollection<CourseReview> CourseReviews { get; set; }
        public virtual ICollection<CoursesToUser> CoursesToUsers { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}
